[default]
font_size = 16
line_height = 18
y_text_start = 7
x_with_sprite = 69
x_no_sprite = 11
initial_asterisk_offset = -1
character_extra_offset = 0
space_extra_offset = 0

[Determination-Mono]
font_size = 16
line_height = 18
y_text_start = 7
x_with_sprite = 69
x_no_sprite = 11
initial_asterisk_offset = -1
character_extra_offset = 0
space_extra_offset = 0

[Comic-Sans]
font_size = 14
line_height = 18
y_text_start = 10
x_with_sprite = 69
x_no_sprite = 11
initial_asterisk_offset = 2
character_extra_offset = 1
space_extra_offset = 2

[Papyrus]
font_size = 15
line_height = 18
y_text_start = 7
x_with_sprite = 70
x_no_sprite = 12
initial_asterisk_offset = -4
character_extra_offset = 0
space_extra_offset = 0

[Wingdings]
font_size = 16
line_height = 18
y_text_start = 7
x_with_sprite = 64
x_no_sprite = 6
initial_asterisk_offset = -4
character_extra_offset = 1
space_extra_offset = 0
